### ISSUE TITLE
Error when running 'run_sims.m'

### ISSUE THREAD

**Issue by Jane-kei** [mdecea/power_handling_Si_resonators#1]
Hello, I got one problem when running 'run_sims.m'.

get_steady_state>@(x)equilibrium(x,Wl,Pin,T0)
(第 41 行)
输入参数太多。

error file 'get_steady_state.m'
error line code: [a_steady, ~, exitflag, ~] = fsolve(@(x) equilibrium(x, Wl, Pin, T0), [real(a_steady)*1e16 imag(a_steady)*1e16], opt);

I have tried severals ways to fix this problem, but don't work.
Could you please tell me which the matlab version that you used to run this program?  Thanks a lot.

**Comment by mdecea** [comment]
Hello,

I can run the code without any problem with Matlab R2020a. Which version are you using? 

One thing you could try is to substitute the `~` in the code by random variable names. I know older versions of Matlab do not support the use of `~` as a placeholder for unused variables. 
Another thing you could try is to not pass the "opt" argument to fsolve ( `[a_steady, ~, exitflag, ~] = fsolve(@(x) equilibrium(x, Wl, Pin, T0), [real(a_steady)*1e16 imag(a_steady)*1e16]`). Maybe older versions of Matlab do not support the pass of options like that. 

Let me know if you succeed! Else, I can take a closer look.

**Comment by Jane-kei** [comment]
> Hello,
> 
> I can run the code without any problem with Matlab R2020a. Which version are you using?
> 
> One thing you could try is to substitute the `~` in the code by random variable names. I know older versions of Matlab do not support the use of `~` as a placeholder for unused variables.
> Another thing you could try is to not pass the "opt" argument to fsolve ( `[a_steady, ~, exitflag, ~] = fsolve(@(x) equilibrium(x, Wl, Pin, T0), [real(a_steady)*1e16 imag(a_steady)*1e16]`). Maybe older versions of Matlab do not support the pass of options like that.
> 
> Let me know if you succeed! Else, I can take a closer look.

I tried again and find the problem. I didn't replace the 'trial' with '.mat files'. So could you please tell me what data can I try to input? 

sim_name = 'trial';  %Name that the .mat files containing sim data will have

% The parameters for the ring shoul be specified in the script
% get_ring_params

**Comment by Jane-kei** [comment]
Hello, the problem solved with MATLAB Online R2021a.

**Comment by mdecea** [comment]
Great to hear!

**Comment by Jane-kei** [comment]
Thanks! %  
If I try to replace 'trial' with '.mat' file,   /sim_name = 'trial';  %Name that the .mat files containing sim data will have/
should I include the inputs data showed below?

Inputs
% ------
% Wl --> Laser freq
% T0 --> Ambient Temperature
% deltaT --> Temperature difference from ambient T (K)
% deltaN --> Free carrier concentration with respect to equilibrium (m^-3)
% Vpn --> Voltage in the pn junction (V)

**Comment by mdecea** [comment]
I don’t really understand your question. 

The parameter `sim_name` corresponds to the name of the output files generated by the simulation. If you set `sim_name = ring`, then once the simulation is ran, a file named `ring.mat` will be created, which will contain all the data. 

You need to modify the function ‘ring_params’ so that all the parameters correspond to the ring you are trying to simulate.

You should be able to run the simulation with the parameters provided and verify everything works.

**Comment by Jane-kei** [comment]
Thanks! Got it ~

**Comment by Jane-kei** [comment]
Hello, in the file 'ring_params.m'

Vring = 0; % Ring volume (m^3) (not specified becasue of Non Disclosure)

Could you please tell me if there any suggested value of 'Vring'? I have tried '0' and other value, but didn't work. I got the error

 "
Error using parsave (line 3)
Cannot create 'trial_Pout_for_Pin=0.00045_lam=1550.25.mat' because 'data' does not exist.

Error in run_sims (line 76)
parfor j = 1:length(Pin_m)"

**Comment by Jane-kei** [comment]
Hello, I have download the newest matlab version to run this program but still got error, so I would really appreciate it if you could re-upload all the files? Thanks!

**Comment by mdecea** [comment]
I just cloned the repository and ran the code in Matlab R2020a, and I had no problem at all running the code. You need to create a new folder named 'data' in the same path as run_sims.m. 

As for Vring, once again that will depend on what you are trying to simulate. Something in the order of `V_ring = 1e-17` should be a good start. But once again, you need to adapt ALL the parameters in ring_params to whatever you are trying to simulate.
